- name: Mark the node as unschedulable
  command: oc adm cordon {{ restart_node_hostname }}

- name: Attempt 1, Evict pods from the node
  command: oc adm drain {{ restart_node_hostname }}  --force --ignore-daemonsets --delete-local-data --timeout="{{ drain_timeout }}"s
  register: drain_result
  ignore_errors: True

- name: Delete any remaining pods
  command: oc get po --all-namespaces --field-selector 'spec.nodeName={{ restart_node_hostname }},status.phase=Terminating' -o json | oc delete -f -
  when: "'FAILED' in drain_result.stderr"

# If this fails, ocp is probably stopping us from draining this node for a legitimate reason.
- name: Attempt 2, Evict pods from the node
  command: oc adm drain {{ restart_node_hostname }}  --force --ignore-daemonsets --delete-local-data --timeout="{{ drain_timeout }}"s
  when: "'FAILED' in drain_result.stderr"
