---
- name: Create Secret (Docker Registry, Opaque, etc)
  hosts: bastion
  gather_facts: false

  vars_files:
  - roles/ocp4_secret/data/{{ create_secret_file }}.yaml

  roles:
  - k8s_auth
  - ocp4_secret
