---
- name: Create New Namespace for Applications
  hosts: bastion
  gather_facts: false
 
  vars_files:
  - roles/ocp4_namespace/data/{{ ns_src_file }}.yaml
  
  roles:
  - k8s_auth
  - ocp4_namespace
