- name: Grab elasticsearch pod
  shell: "oc get pods -n openshift-logging | grep logging-es-data-master | head -1 | awk '{print $1}'"
  register: es_pod_output

- set_fact:
    es_pod: "{{ es_pod_output.stdout }}"

- name: Cleanup orphaned indices in EFK stack
  shell: |
    oc exec -n openshift-logging {{ es_pod }} -- curl -s --key /etc/elasticsearch/secret/admin-key --cert /etc/elasticsearch/secret/admin-cert --cacert /etc/elasticsearch/secret/admin-ca -XDELETE https://localhost:9200/.orphaned*