- include: k8s_login.yaml
- include: ocp4_{{ cls_env }}_new_env.yaml
- include: modify_project_puid.yaml
  # Run when a desired puid to use for running the project is specified.
  when: project_puid is defined and project_puid != "None"
  vars:
    - tmp_project_file: /tmp/"{{ project_name }}".yaml
