apiVersion: v1
kind: Template
metadata:
  name: pv-pvc-template
objects:
  - kind: PersistentVolume
    apiVersion: v1
    metadata:
      name: "{{ project_name }}-nfs-pv"
    spec:
      capacity:
      storage: "{{ pvsize }}Gi"
      accessModes:
      - ReadWriteMany
      persistentVolumeReclaimPolicy: Retain
      nfs:
        path: "{{ nfs_path }}"
        server: "{{ nfs_svr }}"
        readOnly: false
  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: "{{ project_name }}-nfs-pvc"
    spec:
      accessModes:
        - ReadWriteMany
      volumeName: "{{ project_name }}-nfs-pv"
      storageClassName: ""
      resources:
        requests:
          storage: "{{ pv_size }}Gi"
